### PR TITLE
Use context

### PR DESCRIPTION
**Pull request by dillonstreator**
this is a breaking change and would require a v2 tag

### CODE REVIEW

**Comment by DillonStreator** [comment]
@jheth thoughts on this?

**Comment by dillonstreator** [comment]
@jheth can we get this in?

**Comment by jheth** [comment]
Hey @dillonstreator sorry for the delay.  yes, this looks good.

**Comment by jheth** [comment]
@dillonstreator out of curiosity, what was the reason you needed this? In general I support passing context around but what problem did this solve for you?

**Comment by dillonstreator** [comment]
Propagating request cancelation and APM with datadog

**Comment by jheth** [comment]
Excellent. I was actually hoping Datadog was a reason for this. 👍

**Comment by jheth** [comment]
@dillonstreator v2.0.0 tag created

**Pull request merged**
